### ISSUE TITLE
Add support for `Validate` option when provisioning/maintaining ArgoCD applications

### ISSUE THREAD

**Issue by aiforatonyzerbes** [argoproj-labs/terraform-provider-argocd#261]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version
```
Terraform version: v1.3.9 (darwin_arm64)
ArgoCD provider version: v5.1.0
ArgoCD version: v2.6.4+7be094f
```

### Affected Resource(s)
- argocd_application

### Terraform Configuration Files
```hcl
resource "argocd_application" "this" {
  for_each   = {
        for index, tenant in var.tenants: tenant.name => tenant
  }
  metadata {
    name      = "${each.value.name}"
    namespace = "argocd"
  }

  spec {
    project = "myproject"

    destination {
      server    = "https://kubernetes.default.svc"
      namespace = "${each.value.environment}-${each.value.name}"
    }

    source {
      repo_url        = "https://bitbucket.org/team/repo.git"
      path            = "environments/${each.value.environment}/${each.value.name}"
      target_revision = "HEAD"
    }
    
    sync_policy {
      automated {
        prune       = true
        self_heal   = true
        allow_empty = true
      }
      sync_options = ["Validate=false"]
    }
  }
}
```

### Debug Output
```
│ Error: application new-tenant could not be created
│ 
│   with module.argocd-instance.argocd_application.this["new-tenant"],
│   on argocd-instance/applications.tf line 2, in resource "argocd_application" "this":
│    2: resource "argocd_application" "this" {
│ 
│ rpc error: code = InvalidArgument desc = application spec for new-tenant is invalid: InvalidSpecError: Unable to generate manifests in
│ environments/development/new-tenant: rpc error: code = Unknown desc = environments/development/new-tenant: app path does not exist
```
### Panic Output
-

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
The application should be created even though the path in Git is not available. It worked fine using CLI: `argocd app create guestbook --repo $REPO --path environments/development/new-tenant --dest-namespace new-tenant --dest-server https://kubernetes.default.svc --validate=false`

### Actual Behavior
Terraform was unable to create the application on ArgoCD due to the path being absent.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
@aiforatonyzerbes This is expected behaviour at this point. The reason the CLI command works is because you are explicitly providing the flag `--validate=false` (try dropping that and you should get the same error). 

Add support for the validate flag for the provider would be an enhancement.
