### ISSUE TITLE
Error: The terraform-provider-argocd_v6.0.3 plugin crashed!

### ISSUE THREAD

**Issue by AOTHMEN** [argoproj-labs/terraform-provider-argocd#350]
Hello 
I encountered an error while trying to retrieve the target_revision for each application.

![image](https://github.com/oboukili/terraform-provider-argocd/assets/150537445/27c52319-a214-4851-9514-94dac5568789)

**### ERROR** 
 Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).Val
idateDataResourceConfig request was cancelled.
╵

**Stack trace from the terraform-provider-argocd_v6.0.3 plugin:**

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27df929]

goroutine 618 [running]:
github.com/oboukili/terraform-provider-argocd/internal/provider.newApplicationStatus({{0x0, 0x0, 0x0}, {{0xc00196dbc0, 0x7}, {{{...}, {...}, {...}, 0x0, 0x0, ...}, ...}, ...}, ...})
	github.com/oboukili/terraform-provider-argocd/internal/provider/model_application.go:1032 +0xe9
github.com/oboukili/terraform-provider-argocd/internal/provider.readApplication({0x36b9538, 0xc00399f9e0}, 0xc000b82000, 0xc004fb4790)
	github.com/oboukili/terraform-provider-argocd/internal/provider/data_source_application.go:131 +0x3b8
github.com/oboukili/terraform-provider-argocd/internal/provider.(*applicationDataSource).Read(0xc0005c95b8, {0x36b9538, 0xc00399f9e0}, {{{{0x36c6aa0, 0xc0039b5b90}, {0x2b930e0, 0xc0039b3d10}}, {0x36cd460, 0xc0008e5ac0}}, {{{0x0, ...}, ...}, ...}}, ...)
	github.com/oboukili/terraform-provider-argocd/internal/provider/data_source_application.go:86 +0x34d
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc000856c60, {0x36b9538, 0xc00399f9e0}, 0xc00399fad0, 0xc0010d3408)
	github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/fwserver/server_readdatasource.go:79 +0x44e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc000856c60, {0x36b9538?, 0xc00399f890?}, 0xc0039941c0)
	github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/proto6server/server_readdatasource.go:55 +0x28d
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadDataSource({0xc000db70e0, 0xc000db7140, {0xc0009d8140, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadDataSource.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc0004d2f00, {0x36b9538?, 0xc00399edb0?}, 0xc00399a370)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:656 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x2f101a0?, 0xc0004d2f00}, {0x36b9538, 0xc00399edb0}, 0xc00070c2a0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:455 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005423c0, {0x36c7680, 0xc000274680}, 0xc00399dd40, 0xc0010b81e0, 0x504e1d0, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0005423c0, {0x36c7680, 0xc000274680}, 0xc00399dd40, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

**Error: The terraform-provider-argocd_v6.0.3 plugin crashed!**

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by mkilchhofer** [comment]
Could you share some details about your application that helps to reproduce this issue? Eg. a `kubectl get application -o yaml` of your application related to this terraform code.

**Comment by onematchfox** [comment]
Please see comment above
