### ISSUE TITLE
Add support of templatePatch in ApplicationSet (on ArgoCD 2.10)

### ISSUE THREAD

**Issue by dtrouillet** [argoproj-labs/terraform-provider-argocd#368]
### Description

A new parameter named `templatePatch` allow to add more control on Application template in ApplicationSet. More information [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#template-patch)

### Potential Terraform Configuration

```hcl
locals {
  mytemplate = <<EOT
      spec:
      source:
        helm:
          valueFiles:
          {{- range $valueFile := .valueFiles }}
            - {{ $valueFile }}
          {{- end }}
    {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: {{ .prune }}
    {{- end }}
    EOT
  project = "my-project"
}

resource "argocd_application_set" "test" {
  metadata {
    name      = "my-applicationset"
    namespace = "argocd"
  }

  spec {
    generator {
      clusters {
        selector {
          match_labels = {
            "env" = "qa"
          }
        }
      }
    }
    go_template = true
    templatePatch = local.mytemplate
    template {
      metadata {
        name = "test-{{ .name }}"
      }
      spec {
        destination {
          namespace = "my-ns"
          server    = "{{ .server }}"
        }
        project = local.project

        source {
          repo_url        = "{{ .url  }}"
          path            = "{{ .chart  }}"
          target_revision = "{{ .branch  }}"
        }
      }
      source {
        repo_url        = "{{ .url }}"
        ref             = "local"
        target_revision = "{{ .branch }}"
        path            = ""
      }
    }
  }
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by KyriosGN0** [comment]
Hey, I would like to work on this, 
I'll try to open a PR this weekend

**Comment by KyriosGN0** [comment]
Hi, @dtrouillet, @onematchfox, in order to use templatePatch from the go package we need to update to argocd go dep to 2.10 at least, 
is there some guide on how to upgrade dependency of the project?

**Comment by KyriosGN0** [comment]
@dtrouillet is there a plan to upgrade the argocd dep to 2.10+ ?

**Comment by the-technat** [comment]
@KyriosGN0 would you mind opening an issue for the dep update? Then we can discuss about the update there.

But from my point of view it's something we have to do soon as it's also sort of linked to #443

**Comment by KyriosGN0** [comment]
I'll try to take a look in the next couple of days since the bump wad merged

**Comment by the-technat** [comment]
@KyriosGN0 do you want that I assign you the issue?

**Comment by KyriosGN0** [comment]
@the-technat yes thank you

**Comment by asvataa** [comment]
+1
