### ISSUE TITLE
Add support for application inputs

### ISSUE THREAD

**Issue by dtelaroli** [argoproj-labs/terraform-provider-argocd#396]
### Description

The provider is built without application fields:

[spec.source.helm.version](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L106C40-L106C61)
[spec.ignore_difference.managed_fields_managers](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L324)

![image](https://github.com/argoproj-labs/terraform-provider-argocd/assets/536500/aeb1fc0b-3c03-4569-9cc7-fa60c84c241e)

### Potential Terraform Configuration

```hcl
resource "argocd_application" "main" {
  spec {
    source {
      helm {
        version = "v3"
        value_files = [
          "values.yaml"
        ]
      }
    }

    ignore_difference {
      group = "*"
      kind  = "*"
      json_pointers = [
        "/spec/replicas",
      ]
      managed_fields_managers = [
        "argocd-server"
      ]
    }
  }
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tonedefdev** [comment]
I have submitted a PR for this and will happily work on this issue as it's something I was also looking to leverage :)
