### ISSUE TITLE
Future of this provider?

### ISSUE THREAD

**Issue by drdkmkkr** [argoproj-labs/terraform-provider-argocd#407]
Hi,

We really like this provider and are willing to put in some hours to work on more issues to keep it progressing. However, it seems we have a bottleneck with core maintainers available to review changes. We are not blaming the maintainers at all; you have created an awesome provider!

Is there any way we can help you?

We noticed some time ago that the provider was moved into argoproj-labs, thinking it maybe would result in more maintainers/helping hands or become a more official ArgoCD provider.
>This org is managed by the Argo project maintainers and not part of the CNCF Argo umbrella projects. New repos in this org need to be sponsored and created by one of the Argo project maintainers. The goal is to have a place to collaborate with the community to quickly run experiments, POCs and possibly new features to be later incorporated in one of the Argo projects.
_https://github.com/argoproj-labs_

Thank you!

**Comment by drdkmkkr** [comment]
@onematchfox ^^

**Comment by the-technat** [comment]
Also see https://cloud-native.slack.com/archives/C020XM04CUW/p1691069958275329 for ongoing discussions about the topic.

Currently we are figuring out whether the TF registry will eventually recognize the repo move or if we have to republish the provider.

**Comment by blakepettersson** [comment]
Now this all has been settled, so we are back in business. 

@the-technat @mkilchhofer and myself are new maintainers, along with @oboukili. 

Any help is welcome!

**Comment by blakepettersson** [comment]
Will close since we're active again
