### ISSUE TITLE
argocd terraform plugin crashes

### ISSUE THREAD

**Issue by hadi-alnehlawi** [argoproj-labs/terraform-provider-argocd#414]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version:  v1.7.0
ArgoCD provider version:  6.1.1
ArgoCD version: v2.11.3+3f344d5
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

goroutine 343 [running]:
github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDProjectRead({0x107a9f3e0, 0x14000ffde30}, 0x14000e1b300, {0x10782af40?, 0x14000352c80})
        github.com/oboukili/terraform-provider-argocd/argocd/resource_argocd_project.go:127 +0x148
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000e829a0, {0x107a9f418, 0x14000ef6690}, 0xd?, {0x10782af40, 0x14000352c80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:795 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000e829a0, {0x107a9f418, 0x14000ef6690}, 0x14000e97930, {0x10782af40, 0x14000352c80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:1089 +0x494
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400071c000, {0x107a9f418?, 0x14000ef63c0?}, 0x14000330cc0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:661 +0x400
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x107ab5860?, 0x1400071c000?}}, {0x107a9f418?, 0x14000ef63c0?}, 0x140003307c0?)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:119 +0x264
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x107a9f370?, {0x107a9f418?, 0x14000ef6090?}, 0x140003307c0)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ReadResource.go:35 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x14000ba4320, {0x107a9f418?, 0x1400074dcb0?}, 0x14000728660)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:787 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x1078ef1c0?, 0x14000ba4320}, {0x107a9f418, 0x1400074dcb0}, 0x14000e1ac80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:431 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000036000, {0x107a9f418, 0x1400074dbf0}, {0x107aae3c0, 0x14000cfa340}, 0x140014219e0, 0x14000a13560, 0x1095324e8, 0x0)
        google.golang.org/grpc@v1.59.0/server.go:1343 +0xc6c
google.golang.org/grpc.(*Server).handleStream(0x14000036000, {0x107aae3c0, 0x14000cfa340}, 0x140014219e0)
        google.golang.org/grpc@v1.59.0/server.go:1737 +0x9f0
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.59.0/server.go:986 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.59.0/server.go:997 +0x174

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0x14000300180)
        github.com/hashicorp/go-plugin@v1.5.2/server.go:481 +0x1184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.Serve({0x106bd9181, 0x25}, 0x1400042fa10, {0x0, 0x0, 0x0})
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:315 +0xa48
main.main()
        github.com/oboukili/terraform-provider-argocd/main.go:73 +0x310

goroutine 6 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0x14000394700, 0x0?)
        github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x78
created by github.com/patrickmn/go-cache.runJanitor
        github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0x100

goroutine 32 [IO wait]:
internal/poll.runtime_pollWait(0x12fb4eb68, 0x72)
        runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x14000540400?, 0x140010a0000?, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14000540400, {0x140010a0000, 0x8000, 0x8000})
        internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x14000540400, {0x140010a0000?, 0x0?, 0x10401?})
        net/fd_posix.go:55 +0x28
net.(*conn).Read(0x140005620c8, {0x140010a0000?, 0x1400011ec48?, 0x104741e58?})
        net/net.go:183 +0x34
bufio.(*Reader).Read(0x1400054a3c0, {0x140010b0040, 0x9, 0x1400053a8d0?})
        bufio/bufio.go:237 +0x1e0
io.ReadAtLeast({0x107a700c0, 0x1400054a3c0}, {0x140010b0040, 0x9, 0x9}, 0x9)
        io/io.go:332 +0xa0
io.ReadFull(...)
        io/io.go:351
golang.org/x/net/http2.readFrameHeader({0x140010b0040?, 0x9?, 0x1400011edc8?}, {0x107a700c0?, 0x1400054a3c0?})
        golang.org/x/net@v0.19.0/http2/frame.go:237 +0x58
golang.org/x/net/http2.(*Framer).ReadFrame(0x140010b0000)
        golang.org/x/net@v0.19.0/http2/frame.go:498 +0x84
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0x140010b2000, 0x1?)
        google.golang.org/grpc@v1.59.0/internal/transport/http2_server.go:636 +0x10c
google.golang.org/grpc.(*Server).serveStreams(0x14000564000, {0x107aae3c0?, 0x140010b2000})
        google.golang.org/grpc@v1.59.0/server.go:979 +0x1b4
google.golang.org/grpc.(*Server).handleRawConn.func1()
        google.golang.org/grpc@v1.59.0/server.go:920 +0x44
created by google.golang.org/grpc.(*Server).handleRawConn
        google.golang.org/grpc@v1.59.0/server.go:919 +0x174

goroutine 14 [sleep]:
time.Sleep(0x6fc23ac00)
        runtime/time.go:195 +0x118
sigs.k8s.io/controller-runtime/pkg/log.init.0.func1()
        sigs.k8s.io/controller-runtime@v0.11.0/pkg/log/log.go:63 +0x30
created by sigs.k8s.io/controller-runtime/pkg/log.init.0
        sigs.k8s.io/controller-runtime@v0.11.0/pkg/log/log.go:62 +0x24

goroutine 15 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0x0?)
        github.com/hashicorp/go-plugin@v1.5.2/grpc_broker.go:125 +0x58
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0x1400073e120)
        github.com/hashicorp/go-plugin@v1.5.2/grpc_broker.go:437 +0x40
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
        github.com/hashicorp/go-plugin@v1.5.2/grpc_server.go:88 +0x4b8

goroutine 16 [IO wait]:
internal/poll.runtime_pollWait(0x12fb4f5b8, 0x72)
        runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x140003007e0?, 0x14000885000?, 0x1)
        internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x140003007e0, {0x14000885000, 0x1000, 0x1000})
        internal/poll/fd_unix.go:167 +0x200
os.(*File).read(...)
        os/file_posix.go:31

Error: The terraform-provider-argocd_v6.1.1 plugin crashed!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
@hadi-alnehlawi looks like you missed some of the debug output. I can't see the actual error here. Can you please update?
