### ISSUE TITLE
v7.0.0 : no package available for platform linux_amd64

### ISSUE THREAD

**Issue by oilegor1029** [argoproj-labs/terraform-provider-argocd#437]
Hello, 
when running this provider on version 7.0.0 using linux_amd64 platform, this error appears:

> |
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/oboukili/argocd v7.0.0 does not have a
│ package available for your current platform, linux_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.

linux_amd64 is the one that Terraform Cloud uses, so all TF plan and applies are failing there.

### Terraform Version, ArgoCD Provider Version and ArgoCD Version
```
Terraform version: any
ArgoCD provider version: 7.0.0
ArgoCD version: any
```

### Affected Resource(s)

Complete provider

### Steps to Reproduce

Terraform plan or apply using platform linux_amd64

### Workaround to avoid this issue in the meantime

Not use oboukili 7.0.0:

```
terraform {
  required_providers {
    argocd = {
      source  = "oboukili/argocd"
      version = ">= 6.0.1, < 7.0.0"
    }
  }
}
```

or move all required_providers sources from oboukili to argoproj-labs
```
terraform {
  required_providers {
    argocd = {
      source  = "argoproj-labs/argocd"
      version = ">= 7.0.0"
    }
  }
}
```

**Comment by the-technat** [comment]
In our error message I can see that you still reference the "old" repository

> Provider registry.terraform.io/oboukili/argocd v7.0.0 does not have a

Have you updated your versions.tf and the `required_providers` section accordingly?

**Comment by mkilchhofer** [comment]
We opened a HashiCorp support case for this: https://support.hashicorp.com/hc/en-us/requests/162829

Are you okay with the version constraint "< 7.0.0" until we get an update from HashiCorp?

**Comment by camalot** [comment]
We reference `oboukili/argocd >= 6.0.1` and are getting the same: 

```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/oboukili/argocd v7.0.0 does not have a
│ package available for your current platform, linux_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
```

**Comment by oilegor1029** [comment]
> In your error message I can see that you still reference the "old" repository.
> 
> > Provider registry.terraform.io/oboukili/argocd v7.0.0 does not have a
> 
> Have you updated your versions.tf and the `required_providers` section accordingly?

Yep, we have found a required_providers block inside a submodule that is still using the old provider. If we change all the required_providers to the new one (argoproj-labs), tf plans and applies work correctly.



> We opened a HashiCorp support case for this: https://support.hashicorp.com/hc/en-us/requests/162829
> 
> **Our theory was:**
> 
> * we sign the provider version 7.0.0 with the new GPG key where only the new location (argoproj-labs) has the relevant public key
> * the old location (oboukili) should not receive the 7.0.0 release
> 
> **But:**
> 
> * Instead the old location received the event that there is a new version available BUT did not pick up any of the released ZIP archives since they do not match the correct GPG key.
> 
> Are you okay with the version constraint "< 7.0.0" until we get an update from HashiCorp?

Of course, while our submodules are updated to use the new provider (or oboukili gets the new zips), we have set oboukili < 7.0.0 in the workspace to avoid the problem (I'll try to edit the Issue description, in the "Workaround to avoid this issue in the meantime" section I put the new version by mistake)

The problem is avoidable, I opened the Issue just to let you know that those platforms were missing in the old one 😄

**Comment by mkilchhofer** [comment]
At least it should be possible to unpublish a provider version via HashiCorp support:

> ## How do I remove a published version?
> 
> If you remove a version of a provider, module, or policy library from the Terraform Registry, you will break the configuration of any individuals using that version. For this reason, _we never recommend removing previously published versions_ of providers, modules, or policy libraries.
> 
> There are a few situations where you may need to remove a version from the Terraform Registry. For example, if a version has a critical security vulnerability.
> 
> In these situations, your options for removing previously published versions vary on the type of Terraform Registry artifact:
> 
> - **Modules**: The module owner can use the Terraform Registry to [remove a specific version, all versions of a specific module provider, or the module entirely](/terraform/registry/modules/publish#removing-published-content).
> - **Providers**: There is no manual process for removing a version of a provider. [Reach out to us via email](/terraform/registry#getting-help) if it is critical that a version be deleted.
> - **Policy Libraries**: The owner of a policy library can completely [remove it from the Registry through the website](/terraform/registry/policy-libraries/publishing#removing-a-policy-library).
>
> _Source: https://developer.hashicorp.com/terraform/registry/faq#how-do-i-remove-a-published-version_

Hopefully we get an answer from HC tomorrow or so. 🤞

**Comment by agray-ctm** [comment]
For those struggling with broken pipelines due to remote state. Fiddle and adapt as you wish :)

```
#!/bin/bash
set -ex

# Expects $TF_BACKEND_BUCKET, $TF_KEY, and $TF_BACKEND_DYNAMODB_TABLE
# These correspond to -backend-config="bucket=..." -backend-config="key=..." -backend-config="dynamodb_table=..."
TF_FILE=$(basename "$TF_KEY")

aws s3api get-object --bucket "$TF_BACKEND_BUCKET" --key "$TF_KEY" "$(basename "$TF_FILE")"

terraform state replace-provider -state "$TF_FILE" -auto-approve -no-color "registry.terraform.io/oboukili/argocd" "registry.terraform.io/argoproj-labs/argocd"

aws s3 cp "$TF_FILE" "s3://$TF_BACKEND_BUCKET/$TF_KEY" --sse --metadata "Content-Type=application/json"

# The file digest
TF_DIGEST=$(cat "$TF_FILE" | md5sum | awk '{print $1}')

aws dynamodb update-item --table-name "$TF_BACKEND_DYNAMODB_TABLE" --key "{\"LockID\": {\"S\": \"$TF_BACKEND_BUCKET/$TF_KEY-md5\"}}" --attribute-updates "{\"Digest\": {\"Value\": {\"S\": \"$TF_DIGEST\"},\"Action\": \"PUT\"}}" --return-values UPDATED_NEW | jq '.Attributes.RuleSetVersion.S'

rm "$TF_FILE"
```

**Comment by almightyfoon** [comment]
Another work around for people with remote state, its a two step process though. First update your providers block to the below and apply it.

```
terraform {
  required_providers {
    argocd = {
      source = "argoproj-labs/argocd"
      version = ">= 7.0.0"
    }
    depricated-argo = {
      source = "oboukili/argocd"
      version = "< 7.0.0"
    }
  }
}
```

```
Initializing the backend...
Initializing provider plugins...
- Finding argoproj-labs/argocd versions matching ">= 7.0.0"...
- Finding oboukili/argocd versions matching "< 7.0.0"...
- Finding latest version of hashicorp/aws...
- Installing argoproj-labs/argocd v7.0.0...
- Installed argoproj-labs/argocd v7.0.0 (self-signed, key ID 6421DA8DFD8F48D0)
- Installing oboukili/argocd v6.2.0...
- Installed oboukili/argocd v6.2.0 (self-signed, key ID 09A6EABF546E8638)
- Installing hashicorp/aws v5.70.0...
- Installed hashicorp/aws v5.70.0 (signed by HashiCorp)
```

Then remove the depricated-argo block and reapply it. Annoying but it works.

**Comment by agray-ctm** [comment]
> <

Not sure this will work for everybody with nested providers. TF will still try to download the providers from the remote statefile in the init step, no?

**Comment by almightyfoon** [comment]
> > <
> 
> Not sure this will work for everybody with nested providers. TF will still try to download the providers from the remote statefile in the init step, no?

It will, but the 6.2 version satisfies the condition, and swaps the dependency to the new one.

**Comment by mkilchhofer** [comment]
HashiCorp could fix the issue with the missing version on the old location:

> HI Marco,
> 
> My name is Phil and I'm part of the HashiCorp Terraform Registry, I removed the Github Connection from the old namespace oboukili/argocd, to ensure that new releases will not arrive in the old location, you need to remove the Registry Webhooks from the Repository too. I will remove also the version 7.0.0 for you.
> 
> Thank you,
> Phil C.

@oilegor1029 @camalot are you okay when we close this issue? :)

**Comment by camalot** [comment]
@mkilchhofer We are currently pinned with the workaround of `< 7.0.0`. Have not had the chance to try to change the location. since the 7.0.0 version is/was removed from the `oboukili/argocd` we should be good.

**Comment by mkilchhofer** [comment]
I close this issue now. HashiCorp support added two warnings:

> Hi Marko,
>  
> I just added the message to the provider documentation and also added a deprecation warning in the CLI - https://registry.terraform.io/providers/oboukili/argocd/6.2.0

They are visible in the registry:
![Terraform registry website](https://github.com/user-attachments/assets/4e030520-5e25-4730-962a-5e0d14e73f94)

And also via Terraform CLI:
![Terraform CLI warning](https://github.com/user-attachments/assets/074a2238-24d0-4d42-b6ce-72e7f16c8ac0)
